sonar.projectKey=nextjs-ecommerce
sonar.projectName=Next.js E-Commerce SSR/SSG
sonar.projectVersion=1.0
sonar.sources=app,components,types
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.exclusions=node_modules/**,.next/**,**/*.test.ts,**/*.spec.ts